version: '2'
services:
  ui:
    container_name: positivery_ui
    build: ui
    ports:
     - "80:80"
    volumes:
      - ./ui/positivery/dist:/usr/share/nginx/app:ro
      - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
networks:
  default:
    external:
      name: positivery
